let masterTab='품목',selectedDocument=null,documentTab='품목 내역';
function masterVendors(){return [...new Set(['한빛 공급','모아 소재','그린 파트너스',...state.orders.map(o=>o.vendor)])].map((name,n)=>({code:'V-'+String(n+1).padStart(3,'0'),name,type:n===2?'제조업체':'공급업체',owner:['김담당','이담당','박담당'][n%3],terms:n%2?'월말 정산':'입고 후 30일',status:'사용 중'}));}
function masterWarehouses(){return [...new Set(state.items.map(i=>i[3]))].map((name,n)=>({code:'WH-'+String(n+1).padStart(2,'0'),name,owner:['물류팀','구매팀','운영팀'][n%3],count:state.items.filter(i=>i[3]===name).length,type:name.includes('원료')?'원료 보관':name.includes('부자재')?'포장재 보관':'제품 보관'}));}
function previewDocuments(){
  const source=company==='epure'?state.items.filter(i=>['FG-001','RM-001','PK-001'].includes(i[0])):state.items.slice(0,3);
  const lines=source.map((i,n)=>({code:i[0],name:i[1],warehouse:i[3],unit:FlowCore.unit(i),qty:[100,200,500][n],received:[60,0,500][n],price:i[6]}));
  const demo={id:'PO-PREVIEW-001',vendor:'한빛 공급',date:'2026.10.07',due:'2026.10.12',status:'부분 입고',lines,preview:true};
  return [demo,...state.orders.map(o=>({id:o.id,vendor:o.vendor,date:o.date,due:'—',status:o.status,lines:[{code:o.itemCode||'미연결',name:o.name,warehouse:state.items.find(i=>i[0]===o.itemCode)?.[3]||'—',unit:state.items.find(i=>i[0]===o.itemCode)?FlowCore.unit(state.items.find(i=>i[0]===o.itemCode)):'EA',qty:o.qty,received:o.received,price:o.price}],preview:false}))];
}
function documentDetail(doc){
  const total=doc.lines.reduce((s,l)=>s+l.qty*l.price,0);
  const tabs=['품목 내역','관련 문서','처리 이력','메모 · 첨부'];
  let body='';
  if(documentTab==='품목 내역') body=table(['품목 · 코드','입고 창고','발주 수량','입고 누계','미입고','진행률','단가','금액'],doc.lines.map(l=>[`<strong>${esc(l.name)}</strong><span class="cell-sub">${esc(l.code)}</span>`,esc(l.warehouse),l.qty+' '+l.unit,l.received+' '+l.unit,`<strong class="${l.qty>l.received?'orange':'green'}">${FlowCore.round(l.qty-l.received)} ${l.unit}</strong>`,`<div class="mini-progress"><span style="width:${Math.min(100,l.received/l.qty*100)}%"></span></div><span class="cell-sub">${Math.round(l.received/l.qty*100)}%</span>`,money(l.price),money(l.price*l.qty)]))+`<div class="document-total"><span>발주 금액 <small>공급가 기준</small></span><strong>${money(total)}</strong></div>`;
  else if(documentTab==='관련 문서') body=doc.preview?table(['문서 유형','문서 번호','처리일','내용','상태'],[['구매 요청','REQ-PREVIEW-001','2026.10.06','3개 품목 구매 요청',pill('승인 완료')],['구매 발주',doc.id,'2026.10.07','한빛 공급 발주',pill('발주 완료')],['구매 입고','GR-PREVIEW-001','2026.10.07','완제품 60 EA 입고',pill('입고 완료')],['구매 입고','GR-PREVIEW-002','2026.10.07','부자재 500 EA 입고',pill('입고 완료')]]):table(['처리일','유형','품목','수량','사유'],state.movements.filter(m=>m.ref===doc.id).map(m=>[m.date,pill(m.type),esc(m.name),m.qty+' '+m.unit,esc(m.note)]));
  else if(documentTab==='처리 이력') body=doc.preview?`<div class="doc-timeline">${[['구매 요청 등록','구매팀 · 김하늘','10.06 10:00'],['구매 요청 승인','팀장 · 민서','10.06 14:20'],['발주 확정','구매팀 · 김하늘','10.07 09:10'],['1차 부분 입고','물류팀 · 이서윤','10.07 11:30']].map(([t,p,d])=>`<div><i></i><section><strong>${t}</strong><p>${p}</p></section><small>${d}</small></div>`).join('')}</div>`:table(['처리일','변경 내용','변동 수량','재고 전후'],state.movements.filter(m=>m.ref===doc.id).map(m=>[m.date,pill(m.type),m.qty+' '+m.unit,m.before+' → '+m.after]));
  else body=doc.preview?`<div class="doc-notes"><div class="note"><span class="avatar">하</span><section><strong>김하늘 <small>구매팀 · 10.07 09:12</small></strong><p>원료는 다음 주 입고 예정입니다. 완제품과 용기를 먼저 받아 주세요.</p></section></div><div class="attachment"><span class="file-symbol">PDF</span><div><strong>발주서_한빛공급_1007.pdf</strong><small>첨부파일 화면 예시 · 248 KB</small></div><span class="pill gray">미리보기 예시</span></div></div>`:`<div class="doc-notes"><p class="subtitle">${doc.lines.length}개 품목 발주 내역입니다.${state.orders.find(o=>o.id===doc.id)?.cancelReason?' 취소 사유: '+esc(state.orders.find(o=>o.id===doc.id).cancelReason):' 등록된 메모·첨부파일이 없습니다.'}</p></div>`;
  return head('구매 발주 상세','품목별 입고 상태와 관련 문서를 함께 확인하세요.',`<button class="button" id="document-back">← 문서 목록</button>`)+`<div class="document-layout"><div><section class="card document-summary"><div class="doc-title"><div><p class="eyebrow">구매 발주</p><h2>${esc(doc.id)}</h2></div>${pill(doc.status)}</div><div class="info-grid">${[['거래처',doc.vendor],['발주일',doc.date],['입고 예정일',doc.due],['담당 부서','구매팀'],['등록 품목',doc.lines.length+'개'],['문서 구분',doc.preview?'화면 예시':'샘플 입력 내역']].map(([k,v])=>`<div><small>${k}</small><strong>${esc(v)}</strong></div>`).join('')}</div></section>${doc.preview?'<div class="hint" style="margin-top:18px">다품목 발주 화면 예시입니다. 이 문서의 수량과 금액은 실제 시안 재고에 반영되지 않습니다.</div>':''}<section class="card" style="margin-top:20px"><div class="toolbar"><div class="tabs">${tabs.map(t=>`<button class="tab ${documentTab===t?'active':''}" data-document-tab="${t}">${t}</button>`).join('')}</div></div>${body}</section></div><section class="card document-sidebar"><h2>문서 진행 현황</h2>${[['구매 요청','완료'],['승인',doc.status==='승인 대기'?'대기':doc.status==='반려'?'반려':'완료'],['발주',['발주 완료','부분 입고','입고 완료'].includes(doc.status)?'완료':'대기'],['입고',doc.status==='입고 완료'?'완료':doc.status==='부분 입고'?'진행 중':'대기']].map(([k,s])=>`<div class="doc-step"><span class="${s==='완료'?'done':''}">${s==='완료'?'✓':'○'}</span><div><strong>${k}</strong><small>${s}</small></div></div>`).join('')}<hr><p class="subtitle">입고 수량은 품목별로 관리합니다. 한 품목이 먼저 도착해도 나머지 품목은 미입고로 표시됩니다.</p></section></div>`;
}
function masterPage(){
  if(page==='documents'){
    const docs=previewDocuments();const selected=docs.find(d=>d.id===selectedDocument);
    if(selected)return documentDetail(selected);
    return head('문서 관리','구매 문서와 품목별 진행 상황을 한곳에서 확인하세요.',`<button class="button primary" data-document="PO-PREVIEW-001">다품목 발주 예시 보기 →</button>`)+`<section class="card">${toolbar(['전체','부분 입고','입고 완료','승인 대기','취소'])}${table(['발주 번호','거래처','품목','발주 금액','상태','구분','상세'],docs.filter(d=>(filter==='전체'||d.status===filter)&&[d.id,d.vendor,...d.lines.map(l=>l.name)].join(' ').includes(query)).map(d=>[d.id,esc(d.vendor),d.lines.length+'개 품목',money(d.lines.reduce((s,l)=>s+l.qty*l.price,0)),pill(d.status),d.preview?pill('화면 예시'):'샘플 입력',`<button class="button" data-document="${esc(d.id)}">상세 보기</button>`]))}</section>`;
  }
  if(page!=='masters')return null;
  let content='';
  if(masterTab==='품목')content=table(['품목 코드','품목명','유형','기본 단위','안전재고','상태','상세'],state.items.filter(i=>i.join(' ').includes(query)).map(i=>[i[0],`<strong>${esc(i[1])}</strong>`,i[2],FlowCore.unit(i),i[5],pill('사용 중'),`<button class="button" data-master-item="${esc(i[0])}">상세 보기</button>`]));
  if(masterTab==='거래처')content=table(['거래처 코드','거래처명','유형','담당자','결제 조건','상태','상세'],masterVendors().filter(v=>Object.values(v).join(' ').includes(query)).map(v=>[v.code,`<strong>${esc(v.name)}</strong>`,v.type,v.owner,v.terms,pill(v.status),`<button class="button" data-master-vendor="${v.code}">상세 보기</button>`]));
  if(masterTab==='창고')content=`<div class="warehouse-grid">${masterWarehouses().filter(w=>w.name.includes(query)).map(w=>`<button class="warehouse-card" data-master-warehouse="${w.code}"><div><span class="warehouse-icon">${icon('inventory')}</span>${pill('운영 중')}</div><h2>${esc(w.name)}</h2><p>${w.code} · ${w.type}</p><div class="warehouse-info"><span>관리 부서 <b>${w.owner}</b></span><span>보관 품목 <b>${w.count}개</b></span></div><span class="blue">창고 상세 →</span></button>`).join('')}</div>`;
  return head('기준정보 관리','회사 업무의 기준이 되는 품목·거래처·창고 정보를 확인하세요.')+`<section class="card"><div class="toolbar"><div class="tabs">${['품목','거래처','창고'].map(t=>`<button class="tab ${masterTab===t?'active':''}" data-master-tab="${t}">${t}</button>`).join('')}</div><input id="search" class="search" aria-label="목록 검색" placeholder="기준정보 검색" value="${esc(query)}"></div>${content}</section><p class="subtitle">담당자·결제 조건·상세 설정은 화면 구성 예시입니다.</p>`;
}
const detailField=(label,value)=>`<div><small>${label}</small><strong>${esc(value)}</strong></div>`;
function openMasterDetail(kind,key){
  let title,body;
  if(kind==='item'){
    const i=state.items.find(i=>i[0]===key);if(!i)return;
    title=i[1];body=`<span class="pill">${i[2]}</span><p class="subtitle">${i[0]} · 품목 기준정보</p><h3>기본 정보</h3><div class="detail-grid">${detailField('품목명',i[1])}${detailField('품목 코드',i[0])}${detailField('품목 유형',i[2])}${detailField('기본 단위',FlowCore.unit(i))}${detailField('기본 창고',i[3])}${detailField('사용 상태','사용 중')}</div><h3>재고 · 구매 기준</h3><div class="detail-grid">${detailField('현재 정상 재고',i[4]+' '+FlowCore.unit(i))}${detailField('불량 보관',(state.quarantine[i[0]]||0)+' '+FlowCore.unit(i))}${detailField('안전재고',i[5]+' '+FlowCore.unit(i))}${detailField('기준 단가',money(i[6]))}</div><div class="hint">단위 환산 · LOT · 유통기한 관리 여부를 품목별로 설정하는 영역입니다.</div><h3>관리 옵션 <small>화면 예시</small></h3><div class="setting-row"><span>재고 관리 대상</span>${pill('사용')}</div><div class="setting-row"><span>LOT 추적</span>${pill('선택 설정')}</div><div class="setting-row"><span>유통기한 관리</span>${pill('선택 설정')}</div>`;
  }else if(kind==='vendor'){
    const v=masterVendors().find(v=>v.code===key);if(!v)return;title=v.name;body=`${pill(v.type)}<p class="subtitle">${v.code} · 거래처 기준정보</p><h3>기본 정보</h3><div class="detail-grid">${detailField('거래처명',v.name)}${detailField('유형',v.type)}${detailField('담당자',v.owner)}${detailField('사용 상태',v.status)}</div><h3>거래 조건</h3><div class="detail-grid">${detailField('결제 조건',v.terms)}${detailField('통화','KRW · 원화')}${detailField('기본 구매 창고','본사 창고')}${detailField('사업자 정보','등록 영역')}</div><h3>연결된 구매 문서</h3>${table(['발주 번호','품목','상태'],state.orders.filter(o=>o.vendor===v.name).map(o=>[o.id,esc(o.name),pill(o.status)]))}<p class="subtitle">연락처·사업자 정보·정산 정보 입력 영역은 후속 설계에 포함됩니다.</p>`;
  }else{
    const w=masterWarehouses().find(w=>w.code===key);if(!w)return;title=w.name;body=`${pill('운영 중')}<p class="subtitle">${w.code} · 창고 기준정보</p><h3>창고 정보</h3><div class="detail-grid">${detailField('창고명',w.name)}${detailField('창고 유형',w.type)}${detailField('관리 부서',w.owner)}${detailField('위치 정보','창고 주소 입력 영역')}</div><h3>보관 품목</h3>${table(['품목','정상 재고','단위'],state.items.filter(i=>i[3]===w.name).map(i=>[esc(i[1]),i[4],FlowCore.unit(i)]))}<div class="hint">불량 보관 구역 · 로케이션 · 창고 간 이동을 추가할 수 있는 구조입니다.</div>`;
  }
  $('#drawer-title').textContent=title;$('#drawer-body').innerHTML=body;$('#master-drawer').showModal();
}
function bindMaster(){
  document.querySelectorAll('[data-master-tab]').forEach(b=>b.onclick=()=>{masterTab=b.dataset.masterTab;query='';render()});
  document.querySelectorAll('[data-document]').forEach(b=>b.onclick=()=>{selectedDocument=b.dataset.document;documentTab='품목 내역';if(page!=='documents')location.hash='documents';else render()});
  document.querySelectorAll('[data-document-tab]').forEach(b=>b.onclick=()=>{documentTab=b.dataset.documentTab;render()});
  $('#document-back')?.addEventListener('click',()=>{selectedDocument=null;render()});
  document.querySelectorAll('[data-master-item]').forEach(b=>b.onclick=()=>openMasterDetail('item',b.dataset.masterItem));
  document.querySelectorAll('[data-master-vendor]').forEach(b=>b.onclick=()=>openMasterDetail('vendor',b.dataset.masterVendor));
  document.querySelectorAll('[data-master-warehouse]').forEach(b=>b.onclick=()=>openMasterDetail('warehouse',b.dataset.masterWarehouse));
  $('#drawer-close').onclick=()=>$('#master-drawer').close();
}
