let productTabs={settings:'회사 정보',permissions:'구매 담당자',approvalSettings:'구매 요청',calendar:'주간',bom:'BOM 구성',production:'전체',integrations:'연결 현황',reports:'구매 · 판매'};
const previewNotice=()=>'<div class="hint">화면 구성 예시 · 이 화면의 설정과 수치는 실제 서비스에 적용되지 않습니다.</div>';
function productTabsBar(key,values){return `<div class="toolbar"><div class="tabs">${values.map(v=>`<button class="tab ${productTabs[key]===v?'active':''}" data-product-tab="${key}" data-value="${v}">${v}</button>`).join('')}</div><span class="pill gray">화면 예시</span></div>`;}
function previewInput(label,value,type='text'){return `<label class="preview-field">${label}<input type="${type}" value="${esc(value)}" readonly></label>`;}
const previewPanel=(title,body)=>`<section class="card"><div class="card-head"><h2>${title}</h2><span class="pill gray">화면 예시</span></div><div class="product-padding">${body}</div></section>`;
const previewDetailButton=(kind,i,text='상세 보기')=>`<button class="button" data-product-detail="${kind}:${i}">${text}</button>`;
function productPage(){
  const p=page,tab=productTabs[p];let html='';
  if(p==='settings'){
    let body='';
    if(tab==='회사 정보')body=`<div class="company-profile"><span class="company-tile">${company==='epure'?'E':'M'}</span><div><h2>${company==='epure'?'이퓨어':'모아 유통'}</h2><p>독립 ERP 워크스페이스 · ${company==='epure'?'제조 · 유통':'유통'}</p></div>${pill('사용 중')}</div><div class="preview-form">${previewInput('회사명',company==='epure'?'이퓨어':'모아 유통')}${previewInput('기본 통화','KRW · 원화')}${previewInput('기준 시간대','Asia/Seoul')}${previewInput('사업장','본사 · 물류센터')}${previewInput('회계 기준월','1월')}${previewInput('워크스페이스 코드',company==='epure'?'EPURE-DEMO':'MOA-DEMO')}</div><h3>사업장</h3>${table(['사업장 코드','사업장명','담당 조직','상태'],[['HQ','본사','경영지원팀',pill('운영 중')],['DC','물류센터','물류팀',pill('운영 중')]])}`;
    if(tab==='사용 모듈')body=[['erp','구매 · 판매 · 재고','품목과 거래처, 구매·입출고 업무'],['hr','인사 · 근태 · 휴가','구성원과 조직, 근무·휴가 현황'],['manufacturing','제조 관리','BOM, 생산 계획과 진행 현황']].map(([k,t,d])=>`<label class="setting-row"><div><strong>${t}</strong><p>${d}</p></div><input class="switch" type="checkbox" data-module="${k}" ${state.modules[k]?'checked':''} aria-label="${t} 모듈"></label>`).join('')+`<p class="subtitle">모듈 선택은 이 브라우저의 시안 메뉴에만 반영됩니다.</p><div class="setting-row"><div><strong>샘플 데이터 초기화</strong><p>현재 회사의 기존 입력 내역을 처음 상태로 돌립니다.</p></div><button class="button" id="reset">초기화</button></div>`;
    if(tab==='단위 · 번호 규칙')body=`<h3>단위 기준</h3>${table(['단위 코드','단위명','수량 자릿수','사용 대상'],[['EA','개','정수','완제품 · 상품 · 부자재'],['KG','킬로그램','소수 3자리','원료 · 반제품'],['BOX','박스','정수','포장 단위 예시']])}<h3>문서 번호 규칙</h3>${table(['문서 유형','접두어','연월','일련번호','생성 예시'],[['구매 발주','PO','YYYYMM','4자리','PO-202610-0001'],['판매 주문','SO','YYYYMM','4자리','SO-202610-0001'],['생산 지시','MO','YYYYMM','4자리','MO-202610-0001']])}`;
    return head('회사 설정','회사의 기본 기준과 사용할 업무 모듈을 확인하세요.')+previewNotice()+`<section class="card">${productTabsBar('settings',['회사 정보','사용 모듈','단위 · 번호 규칙'])}<div class="product-padding">${body}</div></section>`;
  }
  if(p==='permissions'){
    const roles=['관리자','구매 담당자','물류 담당자','인사 담당자'];
    const rules=[['품목 · 거래처','공통'],['구매 · 발주','구매'],['입고 · 출고','물류'],['재고 조정','물류'],['구성원 정보','인사'],['근태 · 휴가','인사'],['회사 · 권한 설정','관리자']];
    return head('권한 설정','직무별로 접근 범위와 처리 권한을 구분하세요.')+previewNotice()+`<div class="role-layout"><section class="card role-list"><h2>역할</h2>${roles.map(r=>`<button class="role-option ${tab===r?'selected':''}" data-product-tab="permissions" data-value="${r}"><span>${r}</span><small>${r==='관리자'?'전체 업무 관리':r.replace(' 담당자','')+' 업무 중심'}</small></button>`).join('')}</section><section class="card"><div class="card-head"><h2>${tab}</h2><span class="pill">역할 미리보기</span></div>${table(['업무 영역','조회','등록','수정','승인','내보내기'],rules.map(([title,area])=>{let own=tab==='관리자'||tab.startsWith(area);return [title,...[own||area==='공통',own,own,tab==='관리자',own].map((v,n)=>`<input type="checkbox" class="switch" ${v?'checked':''} disabled aria-label="${title} ${['조회','등록','수정','승인','내보내기'][n]}">`)]}))}<div class="product-padding"><h3>데이터 접근 범위</h3><div class="scope-chips"><span>회사 전체</span><span class="selected">소속 부서</span><span>본인 담당 건</span></div><p class="subtitle">민감한 직원 정보와 원가 정보는 별도 권한으로 분리하는 예시입니다.</p></div></section></div>`;
  }
  if(p==='approvalSettings'){
    return head('승인 절차 설정','문서 유형과 금액에 따라 승인 순서를 구성하세요.')+previewNotice()+`<section class="card">${productTabsBar('approvalSettings',['구매 요청','재고 조정','휴가 신청'])}<div class="product-padding"><div class="approval-flow">${[['신청','업무 담당자'],['1차 승인','소속 팀장'],['최종 승인',tab==='구매 요청'?'경영지원 담당':'업무 관리자']].map(([t,n],i)=>`<div class="approval-step"><span>${i+1}</span><h3>${t}</h3><p>${n}</p>${pill(i===0?'신청자':'승인자')}</div>${i<2?'<b class="flow-arrow">→</b>':''}`).join('')}</div><h3>승인 규칙</h3>${table(['조건','승인 경로','반려 처리','대결자'],tab==='구매 요청'?[['100만원 미만','팀장 승인','신청자에게 반환','부서 대결자'],['100만원 이상','팀장 → 경영지원','신청자에게 반환','부서 대결자']]:tab==='재고 조정'?[['모든 수량 조정','물류 팀장 → 관리자','재실사 요청','물류 대결자']]:[['연차 · 반차','소속 팀장','신청자에게 반환','부서 대결자']])}<div class="setting-row"><span>승인자 부재 시</span>${pill('대결자에게 전달')}</div><div class="setting-row"><span>승인 완료 후 수정</span>${pill('재승인 필요')}</div></div></section>`;
  }
  if(p==='people'){
    return head('구성원','직원의 기본 정보와 소속 조직을 한곳에서 확인하세요.',`<a class="button" href="#organization">조직도 보기 →</a>`)+`<section class="card">${toolbar(['전체','근무 중','외근','휴가'])}${table(['구성원','부서','직책','입사일','고용 형태','오늘 근무','상세'],people.filter(v=>(filter==='전체'||v[3]===filter)&&v.join(' ').includes(query)).map(v=>[`<div class="person"><span class="avatar">${v[0][0]}</span><strong>${v[0]}</strong></div>`,v[1],v[2],'2025.03.01','정규직',pill(v[3]),previewDetailButton('employee',people.indexOf(v))]))}</section><p class="subtitle">입사일·고용 형태·개인 상세는 샘플 정보입니다.</p>`;
  }
  if(p==='organization'){
    return head('조직도','부서와 구성원, 승인 관계를 확인하세요.')+previewNotice()+`<section class="card org-board"><div class="org-root"><span class="company-tile">${company==='epure'?'E':'M'}</span><h2>${company==='epure'?'이퓨어':'모아 유통'}</h2><small>본사 · ${people.length}명</small></div><div class="org-connector"></div><div class="org-teams">${['경영지원팀','구매 · 물류','운영 · 상품','개발팀'].map((name,n)=>`<div class="org-team"><h3>${name}</h3>${people.filter((v,i)=>n===0?i===0:n===1?[2,3].includes(i):n===2?[1,4].includes(i):i===5).map(v=>`<button data-product-detail="employee:${people.indexOf(v)}"><span class="avatar">${v[0][0]}</span><span><strong>${v[0]}</strong><small>${v[2]} · ${v[1]}</small></span></button>`).join('')}</div>`).join('')}</div></section>`;
  }
  if(p==='calendar'){
    return head('근무 · 휴가 캘린더','팀의 근무 일정과 휴가, 정정 요청을 확인하세요.')+previewNotice()+`<section class="card"><div class="card-head"><h2>2026년 10월 5일 – 11일</h2><span class="pill">주간 일정</span></div><div class="week-scroll"><div class="week-calendar"><div class="week-heading">구성원</div>${['월 5','화 6','수 7','목 8','금 9'].map((d,i)=>`<div class="week-heading ${i===2?'current-day':''}">${d}</div>`).join('')}${people.map((v,i)=>`<div class="week-person"><span class="avatar">${v[0][0]}</span><span>${v[0]}<small>${v[1]}</small></span></div>${Array.from({length:5},(_,d)=>{let vacation=(i===1&&d===3)||(i===4&&d===2),remote=i===2&&d===2;return `<div class="week-cell ${d===2?'current-day':''}"><span class="schedule ${vacation?'vacation':remote?'remote':''}">${vacation?'연차':remote?'외근':'09:00 – 18:00'}</span>${i===0&&d===1?'<span class="request-dot">정정 요청</span>':''}</div>`}).join('')}`).join('')}</div></div></section><section class="card" style="margin-top:22px"><div class="card-head"><h2>근태 정정 요청</h2></div>${table(['신청자','대상일','기존 기록','정정 요청','사유','상태','상세'],[['민서','2026.10.06','출근 미기록','09:00 출근','출근 기록 누락',pill('승인 대기'),previewDetailButton('correction',0)]])}</section>`;
  }
  if(p==='availability'){
    return head('가용재고','보유 재고와 주문 예약을 구분해 출고 가능한 수량을 확인하세요.')+previewNotice()+`<div class="stats">${stat('관리 품목',state.items.length,'개','현재 시안 품목')}${stat('예약 품목',state.items.filter(i=>i[4]>0).length,'개','예약 수량은 화면 예시','blue')}${stat('부족 품목',state.items.filter(i=>i[4]<i[5]).length,'개','안전재고 미만','orange')}${stat('예약 기준','출고 전','','주문 확정 시 예약하는 예시')}</div><section class="card">${table(['품목','창고','보유 정상재고','예약 수량','가용재고','불량 보관','단위'],state.items.map(i=>{let reserved=Math.min(i[4],Math.ceil(i[4]*.2));return [`<strong>${esc(i[1])}</strong><span class="cell-sub">${i[0]}</span>`,i[3],i[4],reserved,`<strong class="blue">${FlowCore.round(i[4]-reserved)}</strong>`,state.quarantine[i[0]]||0,FlowCore.unit(i)]}))}</section><div class="hint" style="margin-top:20px">가용재고 = 정상 보유 재고 − 예약 수량. 예약 수량은 시각적 예시이며 실제 주문 예약 기능은 연결하지 않았습니다.</div>`;
  }
  if(p==='transfers'){
    return head('창고 이동','출발 창고에서 이동 중 재고를 거쳐 도착 창고로 인계합니다.')+previewNotice()+`<div class="transfer-route"><section class="card"><span class="route-label">출발 창고</span><h2>본사 창고</h2><p>출고 담당 · 물류팀</p>${pill('이동 출고 완료')}</section><div class="transfer-arrow">→<small>이동 중 20 EA</small></div><section class="card"><span class="route-label">도착 창고</span><h2>물류센터</h2><p>입고 담당 · 물류팀</p>${pill('입고 확인 대기')}</section></div><section class="card"><div class="card-head"><h2>이동 요청 목록</h2></div>${table(['이동 번호','품목','출발 → 도착','수량','상태','상세'],[['TR-202610-001',esc(state.items[0]?.[1]||'샘플 상품'),'본사 → 물류센터','20 EA',pill('이동 중'),previewDetailButton('transfer',0)],['TR-202610-002','포장 부자재','물류센터 → 본사','100 EA',pill('이동 완료'),previewDetailButton('transfer',1)]])}</section>`;
  }
  if(p==='bom'){
    const raw=state.items.find(i=>i[2]==='원료'),pack=state.items.find(i=>i[2]==='부자재');
    return head('BOM 관리','제품 구성과 버전별 소요량, 예상 재료비를 확인하세요.')+previewNotice()+`<section class="card"><div class="card-head"><div><h2>${esc(state.items[0]?.[1]||'샘플 제품')}</h2><small>BOM-001 · 1개 생산 기준</small></div><span class="pill">v1.1 · 사용 중</span></div>${productTabsBar('bom',['BOM 구성','버전 이력'])}${tab==='버전 이력'?table(['버전','적용일','변경 내용','담당자','상태'],[['v1.1','2026.10.01','원료 배합량 수정','상품팀',pill('사용 중')],['v1.0','2026.08.01','최초 등록','상품팀',pill('이전 버전')]]):table(['구성 품목','유형','소요량','단위','기준 단가','예상 재료비'],[[raw?.[1]||'기본 원료','원료','0.06','kg',money(raw?.[6]||7500),money((raw?.[6]||7500)*.06)],[pack?.[1]||'제품 포장재','부자재','1','EA',money(pack?.[6]||850),money(pack?.[6]||850)],['제품 라벨','부자재','1','EA',money(150),money(150)]])}</section><div class="stats" style="margin-top:22px">${stat('구성 품목','3','개','원료와 포장 부자재')}${stat('생산 기준','1','EA','제품 1개 기준')}${stat('예상 재료비',money((raw?.[6]||7500)*.06+(pack?.[6]||850)+150),'','노무·경비는 제외')}${stat('BOM 버전','v1.1','','적용일 2026.10.01')}</div>`;
  }
  if(p==='production'){
    const jobs=[['MO-202610-001',state.items[0]?.[1]||'샘플 제품',1000,720,'생산 중'],['MO-202610-002',state.items[1]?.[1]||'두 번째 제품',500,0,'자재 대기'],['MO-202610-003','포장 공정',800,800,'완료']];
    return head('생산 현황','생산 계획과 실적, 필요한 자재를 함께 확인하세요.')+previewNotice()+`<div class="stats">${stat('생산 중','1','건','진행 중인 생산 지시','blue')}${stat('자재 대기','1','건','소요량 부족 확인','orange')}${stat('완료','1','건','실적 등록 완료','green')}${stat('오늘 생산 실적','720','EA','화면 예시')}</div><section class="card">${productTabsBar('production',['전체','생산 중','자재 대기','완료'])}${table(['생산 지시','품목','계획 수량','실적','진행률','상태','상세'],jobs.filter(j=>tab==='전체'||tab===j[4]).map((j,i)=>[j[0],esc(j[1]),j[2]+' EA',j[3]+' EA',`<div class="mini-progress"><span style="width:${j[3]/j[2]*100}%"></span></div><small>${Math.round(j[3]/j[2]*100)}%</small>`,pill(j[4]),previewDetailButton('production',jobs.indexOf(j))]))}</section>`;
  }
  if(p==='integrations'){
    return head('연동 관리','외부 시스템의 연결 상태와 동기화 결과를 확인하세요.')+previewNotice()+`<section class="card">${productTabsBar('integrations',['연결 현황','품목 매핑','오류 내역'])}${tab==='연결 현황'?`<div class="integration-grid">${[['이퓨어 슈퍼 어드민','상품 · 주문 · 배송','연결 예시'],['이카운트','기준정보 · 기초 재고 이전','이전 예시'],['배송 서비스','운송장 · 배송 상태','미연결 예시']].map(([t,d,s])=>`<section class="integration-card"><span class="integration-logo">${t[0]}</span><h2>${t}</h2><p>${d}</p>${pill(s)}<small>실제 계정에 접속하지 않습니다.</small></section>`).join('')}</div>`:tab==='품목 매핑'?table(['외부 상품','ERP 품목 코드','ERP 품목','연결 상태'],state.items.filter(i=>['완제품','상품'].includes(i[2])).map(i=>[esc(i[1]),i[0],esc(i[1]),pill('매핑 예시')])):table(['발생일','연동 항목','원인','상태','상세'],[['10.07 11:20','주문 수신','품목 코드 미연결',pill('확인 필요'),previewDetailButton('integration',0)],['10.07 10:30','재고 전송','응답 시간 초과',pill('재처리 대기'),previewDetailButton('integration',1)]])}</section>`;
  }
  if(p==='reports'){
    const hr=tab==='근태';return head('리포트','업무 지표와 기간별 흐름을 한눈에 확인하세요.')+previewNotice()+`<section class="card">${productTabsBar('reports',['구매 · 판매','재고','근태'])}<div class="product-padding"><div class="report-period">2026년 10월 <span class="pill gray">월간 예시</span></div><div class="stats">${hr?stat('근무 기록률','98.2','%','샘플 집계')+stat('휴가 사용','12.5','일','이번 달 샘플')+stat('정정 요청','3','건','처리 대기')+stat('평균 근무','8','시간','일 평균'):stat(tab==='재고'?'재고 평가액':'구매 금액',tab==='재고'?money(state.items.reduce((sum,i)=>sum+i[4]*i[6],0)):'₩12,800,000','','월간 샘플')+stat(tab==='재고'?'출고 금액':'판매 금액',tab==='재고'?'₩6,720,000':'₩24,600,000','','월간 샘플','blue')+stat('전월 대비','+12.4','%','비교 예시','green')+stat('확인 필요',tab==='재고'?'2':'3','건','미처리 업무')}</div><div class="report-chart"><div class="chart-title"><h2>${hr?'부서별 근무 기록률':tab==='재고'?'주차별 입출고':'주차별 구매 · 판매'}</h2><span>● ${hr?'근무 기록':'구매 / 입고'} <span class="muted">● 판매 / 출고</span></span></div><div class="bar-chart">${[45,68,52,86,74].map((v,i)=>`<div class="bar-group"><div><span class="bar primary-bar" style="height:${v}%"></span>${!hr?`<span class="bar secondary-bar" style="height:${Math.min(100,v+13)}%"></span>`:''}</div><small>${hr?['경영지원','구매','물류','운영','개발'][i]:(i+1)+'주차'}</small></div>`).join('')}</div></div>${hr?table(['부서','구성원','근무 기록률','휴가 사용','정정 대기'],[['경영지원팀','1명','100%','1일','1건'],['구매 · 물류','2명','98%','2.5일','1건'],['운영 · 상품','2명','97%','8일','1건']]):tab==='재고'?table(['품목 유형','관리 품목','현재 재고 평가액','안전재고 미만'],[...new Set(state.items.map(i=>i[2]))].map(type=>{const items=state.items.filter(i=>i[2]===type);return [type,items.length+'개',money(items.reduce((sum,i)=>sum+i[4]*i[6],0)),items.filter(i=>i[4]<i[5]).length+'개']})):table(['구분','이번 달','지난 달','변화'],[['구매 금액',money(12800000),money(11387900),'+12.4%'],['판매 금액',money(24600000),money(22360000),'+10.0%'],['출고 건수','148건','132건','+16건']])}</div></section>`;
  }
  return null;
}
function openProductDetail(kind,index){
  let title,body;
  if(kind==='employee'){
    const p=people[Number(index)];if(!p)return;title=p[0];body=`<div class="employee-profile"><span class="avatar">${p[0][0]}</span><div><h2>${p[0]}</h2><p>${p[1]} · ${p[2]}</p></div>${pill('재직 중')}</div><h3>기본 정보</h3><div class="detail-grid">${detailField('부서',p[1])}${detailField('직책',p[2])}${detailField('입사일','2025.03.01')}${detailField('고용 형태','정규직')}${detailField('사업장','본사')}${detailField('승인자','소속 팀장')}</div><h3>근무 · 휴가</h3><div class="detail-grid">${detailField('기본 근무','09:00 – 18:00')}${detailField('근무 유형','고정 근무')}${detailField('휴가 부여','15일 · 샘플 기준')}${detailField('오늘 상태',p[3])}</div><h3>접근 권한</h3>${pill(p[1]+' 역할')}<p class="subtitle">개인 정보와 근무 정책은 화면 예시입니다.</p>`;
  }else if(kind==='correction'){title='근태 정정 요청';body=`${pill('승인 대기')}<h3>요청 내용</h3><div class="detail-grid">${detailField('신청자','민서')}${detailField('대상일','2026.10.06')}${detailField('기존 기록','출근 미기록')}${detailField('정정 요청','09:00 출근')}</div><h3>정정 사유</h3><p>출근 기록을 누락하여 정정 요청합니다.</p><h3>승인 경로</h3><p>신청자 → 소속 팀장</p><div class="hint">정정 승인 화면 예시입니다. 실제 출퇴근 기록은 변경하지 않습니다.</div>`;
  }else if(kind==='transfer'){title='창고 이동 상세';body=`${pill(Number(index)?'이동 완료':'이동 중')}<h3>이동 경로</h3><div class="detail-grid">${detailField('출발',Number(index)?'물류센터':'본사 창고')}${detailField('도착',Number(index)?'본사 창고':'물류센터')}${detailField('이동 품목',state.items[0]?.[1]||'샘플 품목')}${detailField('수량',Number(index)?'100 EA':'20 EA')}</div><h3>인계 확인</h3><p>이동 출고 → 운송 중 → 도착 확인 → 이동 입고</p><div class="hint">미도착 수량은 이동 중 재고로 구분하는 화면 예시입니다.</div>`;
  }else if(kind==='production'){title='생산 지시 상세';const n=Number(index),status=['생산 중','자재 대기','완료'][n]||'생산 중',plan=[1000,500,800][n]||1000,actual=[720,0,800][n]??720,product=n===2?'포장 공정':state.items[n]?.[1]||'샘플 제품';body=`${pill(status)}<h3>생산 계획</h3><div class="detail-grid">${detailField('생산 품목',product)}${detailField('적용 BOM','v1.1')}${detailField('계획',plan+' EA')}${detailField('실적',actual+' EA')}${detailField('생산 LOT','LOT-20261007-A')}${detailField('작업장','본사 공장')}</div><h3>자재 소요량</h3>${table(['자재','필요 수량','확보 상태'],[['기본 원료','60 kg',pill('확보 완료')],['용기','1,000 EA',pill('확보 완료')],['제품 라벨','1,000 EA',pill('확인 필요')]])}<div class="hint">생산 실적 등록과 원료 차감은 화면 예시입니다.</div>`;
  }else{title='연동 오류 상세';body=`${pill('확인 필요')}<h3>오류 정보</h3><div class="detail-grid">${detailField('대상 시스템','이퓨어 슈퍼 어드민')}${detailField('연동 항목',Number(index)?'재고 전송':'주문 수신')}${detailField('오류 원인',Number(index)?'응답 시간 초과':'품목 코드 미연결')}${detailField('최근 시도','2026.10.07 11:20')}</div><h3>처리 안내</h3><p>연결 정보와 품목 매핑을 확인한 뒤 재처리합니다.</p><div class="hint">실제 API 호출이나 계정 연결은 수행하지 않습니다.</div>`;}
  $('#drawer-title').textContent=title;$('#drawer-body').innerHTML=body;$('#master-drawer').showModal();
}
function bindProduct(){document.querySelectorAll('[data-product-tab]').forEach(b=>b.onclick=()=>{productTabs[b.dataset.productTab]=b.dataset.value;render()});document.querySelectorAll('[data-product-detail]').forEach(b=>b.onclick=()=>{const [kind,index]=b.dataset.productDetail.split(':');openProductDetail(kind,index)});}
